config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  # root 'billing#index', as: 'billing'
  # get '/card/new' => 'billing#new_card', as: :add_payment_method
  # post "/card" => "billing#create_card", as: :create_payment_method
  # get '/success' => 'billing#success', as: :success
  # post '/subscription' => 'billing#subscribe', as: :subscribe



  # get 'charges/new', to: 'charges#new'
  # post 'charges', to: 'charges#create', as: 'create_charges'
  root 'wallet#index'
  get 'wallet/add_amount', to: 'wallet#new', as: 'new_wallet_amount'
  get '/card/new' => 'wallet#new_card', as: 'add_card'
  patch 'wallet/add_amount', to: 'wallet#add', as: 'add_wallet_amount'

  get 'subscribe', to: 'subscribes#new', as: 'subscribe'
  get 'subscribe/recharge', to: 'subscribes#recharge', as: 'recharge_my_account'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/billing_controller.rb
class BillingController < ApplicationController
  before_action :authenticate_user!
  def index
  end

  def new_card
    respond_to do |format|
      format.js
    end
  end
  def create_card
    respond_to do |format|
      if current_user.stripe_id.nil?
        customer = Stripe::Customer.create({"email": current_user.email})
        #here we are creating a stripe customer with the help of the Stripe library and pass as parameter email.
        current_user.update(:stripe_id => customer.id)
        #we are updating current_user and giving to it stripe_id which is equal to id of customer on Stripe
      end
      card_token = params[:stripeToken]
      #it's the stripeToken that we added in the hidden input
      if card_token.nil?
        format.html { redirect_to billing_path, error: "Oops"}
      end
      #checking if a card was giving.
      customer = Stripe::Customer.new current_user.stripe_id
      customer.source = card_token
      #we're attaching the card to the stripe customer
      customer.save
      format.html { redirect_to success_path }
    end
  end
  def success
    @plans = Stripe::Plan.list.data
  end
  def subscribe
    if current_user.stripe_id.nil?
      redirect_to success_path, :flash => {:error => 'Firstly you need to enter your card'}
      return
    end
    #if there is no card
    customer = Stripe::Customer.new current_user.stripe_id
    #we define our customer
    subscriptions = Stripe::Subscription.list(customer: customer.id)
    subscriptions.each do |subscription|
      subscription.delete
    end
    #we delete all subscription that the customer has. We do this because we don't want that our customer to have multiple subscriptions
    plan_id = params[:plan_id]
    subscription = Stripe::Subscription.create({
                                                   customer: customer,
                                                   items: [{plan: plan_id}], })
 #we are creating a new subscription with the plan_id we took from our form

    subscription.save
    redirect_to success_path
  end
end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController
  def new
  end

  def create
    # Amount in cents
    @amount = 500

    customer = Stripe::Customer.create({
      email: params[:stripeEmail],
      source: params[:stripeToken],
    })

    charge = Stripe::Charge.create({
      customer: customer.id,
      amount: @amount,
      description: 'Rails Stripe customer',
      currency: 'usd',
    })

  rescue Stripe::CardError => e
    flash[:error] = e.message
    redirect_to new_charge_path
  end
end

app/controllers/subscribes_controller.rb
class SubscribesController < ApplicationController
  rescue_from Stripe::CardError, with: :catch_exception
  def new
    if current_user.stripe_id.nil?
      customer = Stripe::Customer.create({"email": current_user.email})
      #here we are creating a stripe customer with the help of the Stripe library and pass as parameter email.
      current_user.update(:stripe_id => customer.id)
      #we are updating current_user and giving to it stripe_id which is equal to id of customer on Stripe
    end
  end

  def recharge
    if current_user.stripe_id.nil?
      redirect_to root_path, :flash => {:error => 'Firstly you need to enter your card'}
      return
    end

    if current_user.wallet_amount < 200
      result = ChargeService.new(current_user.email, current_user, 500).call
      if result["paid"] == true
        redirect_to subscribe_path, :flash => {:info => 'Charged successfully'}
      else
        redirect_to subscribe_path, :flash => {:info => 'could not pay'}
      end
    else
      redirect_to root_path, :flash => {:error => 'You have sufficient balance '}
    end

  end
  def catch_exception(exception)
    flash[:error] = exception.message
    redirect_to root_path and return
  end
end

app/controllers/wallet_controller.rb
class WalletController < ApplicationController
  before_action :authenticate_user!
  rescue_from Stripe::CardError, with: :catch_exception
  def index
  end

  def new
  end

  def new_card
  end

  def add
    @wallet_amount = params[:user][:wallet_amount]
    StripeChargesServices.new(params[:stripeToken], current_user.email, current_user, @wallet_amount).call
  end
  def charges_params
    params.permit(:stripeEmail, :stripeToken, :order_id)
  end

  def catch_exception(exception)
    flash[:error] = exception.message
    redirect_to root_path
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/billing_helper.rb
module BillingHelper
end

app/views/billing/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-12 mt-4 text-center">
      <h1> Welcome  "<%= current_user.email %>"</h1>
    </div>
  </div>
  <div class="row">
    <h1 class="col-md-12 mt-5 text-center">
      Are you ready to pay?
    </h1>
  </div>
  <%= form_tag create_payment_method_path, id: "add_payment_method_path" do  %>
    <%= link_to "Let's go", add_payment_method_path, remote: true, class: "btn btn-primary" %>
  <% end %>
</div>

app/views/billing/new_card.js.erb
var handler = StripeCheckout.configure({
    key: '<%= Rails.configuration.stripe[:publishable_key] %>',
    //get a publishable key that we put in editor depending on environment: production or development
    locale: 'auto',
    //handle translation
    name: "Uno",
    description: "Add your credit card information",
    email: "<%= current_user.email %>",
    panelLabel: "Add payment method",
    allowRememberMe: false,
    token: function (token) {
        var form = document.getElementById('add_payment_method_path');
        //we will create element with this id in the next step
        var hiddenInput = document.createElement('input');
        hiddenInput.setAttribute('type', 'hidden');
        hiddenInput.setAttribute('name', 'stripeToken');
        hiddenInput.setAttribute('value', token.id);
        //creating an <input type="hidden" name="stripeToken" value="<id>"/>. We will need this information in the next steps to link a user to his card
        form.appendChild(hiddenInput);
        //adding this input when we use a form.
        form.submit();
    }
});

handler.open();

window.addEventListener('popstate', function() {
    handler.close();
});

app/views/billing/success.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-12 mt-4 text-center">
      <h2>You successfully linked a credit card to your account</h2>
    </div>
  </div>
</div>
<div class="row">
  <div class="col-md-12 mt-3 text-center">
    <h3>Now you need to choose your plan</h3>
  </div>
</div>
<!-- creating a form -->
<%=form_tag subscribe_path, method: :post do %>
<div class="row">
  <div class="col-md-4"></div>
  <div class="col-md-4 text-center">
    <div class="form-group">
      <select class="form-control" name="plan_id">
        <% @plans.each do |plan| %>
        <option value="<%= plan.id %>"><%= plan.amount/100 %>/$ <%= plan.nickname %></option>
        <!-- we pass id chosen by custmer as a value  to use it for subscription -->
        <%end%>
      </select>
    </div>
  </div>
  <div class="col-md-4"> </div>
</div>
&nbsp;
<div class="row">
  <div class="col-md-12 mt-2 text-center">
    <%= submit_tag 'Save changes', class: "btn btn-primary" %>
  </div>
</div>
<% end %>

app/views/charges/create.html.erb
<h2>Thanks, you paid <strong>$5.00</strong>!</h2>

app/views/charges/new.html.erb
<%= form_tag create_charges_path do %>
  <article>
    <% if flash[:error].present? %>
      <div id="error_explanation">
        <p><%= flash[:error] %></p>
      </div>
    <% end %>
    <label for="">fill in the Amount to update your balance</label>
    <br>
    <label class="amount">
      <input type="number" name="amount" step="0.01" value="" id="wallet_amount">
    </label> Current balance :<%= current_user.wallet_amount %>
    <div class="">
      &nbsp;&nbsp;
    </div>
  </article>

<script src="https://checkout.stripe.com/checkout.js"
        class="stripe-button"
        data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
        data-description="A month's subscription"
        data-amount=""
        data-locale="auto"></script>
<script type="text/javascript">
  $('#wallet_amount').change(function () {
    // console.log($(this).val());
    $(".stripe-button").data('amount', $(this).val())
  })
</script>

<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PaymentTest</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'https://checkout.stripe.com/checkout.js' %>
    <script
    src="https://code.jquery.com/jquery-3.4.1.min.js"
    integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo="
    crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  </head>

  <body>
    <% flash.each do |key, value| %>
      <div class="alert alert-<%= key == 'alert' ? 'warning' : key %> alert-dismissible">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        <ul>
          <li>
            <div class="flash"><%= value %></div>
          </li>
        </ul>
      </div>
    <% end %>
    <%= link_to "Home", root_path%>
    <%= link_to "Log Out", destroy_user_session_path, method: :delete %>

    <br>
    <%= yield %>
  </body>
</html>

app/views/subscribes/new.html.erb
<br>
&nbsp;
<%= link_to "Recharge my account", recharge_my_account_path %>

app/views/wallet/add.html.erb
thanks for adding <%= @wallet_amount %>

app/views/wallet/index.html.erb
Welcome user <%= current_user.email %>
<br>
wallet balance <%= current_user.wallet_amount %>
<br>
<%= link_to "add app money to wallet", new_wallet_amount_path  %>
<br>
<%= link_to "go to subscribe", subscribe_path %>

app/views/wallet/new.html.erb
hi this is your page to add wallet balance
<br>
<%= form_for current_user, url: add_wallet_amount_path, html: {id: 'add-wallet-money-method'} do |f| %>
<br>
  <%= f.label :wallet_amount %>
<br>
  <%= f.number_field :wallet_amount %>
<br>
<% end %>
<%= link_to 'submit', add_card_path, remote: true  %>
<script type="text/javascript">
  $('form input').keydown(function (e) {
    if (e.keyCode == 13) {
        e.preventDefault();
        return false;
    }
  });
</script>

app/views/wallet/new_card.js.erb
var handler = StripeCheckout.configure({
    key: '<%= Rails.configuration.stripe[:publishable_key] %>',
    //get a publishable key that we put in editor depending on environment: production or development
    locale: 'auto',
    //handle translation
    name: "Uno",
    description: "Add your credit card information",
    email: "<%= current_user.email %>",
    panelLabel: "Add payment method",
    allowRememberMe: true,
    token: function (token) {
        var form = document.getElementById('add-wallet-money-method');
        //we will create element with this id in the next step
        var hiddenInput = document.createElement('input');
        hiddenInput.setAttribute('type', 'hidden');
        hiddenInput.setAttribute('name', 'stripeToken');
        hiddenInput.setAttribute('value', token.id);
        //creating an <input type="hidden" name="stripeToken" value="<id>"/>. We will need this information in the next steps to link a user to his card
        form.appendChild(hiddenInput);
        //adding this input when we use a form.
        form.submit();
    }
});

handler.open();

window.addEventListener('popstate', function() {
    handler.close();
});